# Clean-Folder-HTML.ps1
# Deletes everything inside a folder and generates an HTML report
#Author : Herwin Yudha Setyawan

$targetPath = "C:\Users\Name\AppData\Local\Temp"
$log = @()
$deletedItems = @()
$skippedItems = @()
$maxRetries = 3
$waitSeconds = 15
$copyright = "Generated by Herwin Yudha Setyawan"
$htmlReport = "C:\Users\Name\AppData\Local\CleanTempReport.html"

# Ensure target exists
if (-not (Test-Path -Path $targetPath)) {
    Write-Output "Folder does not exist: $targetPath"
    exit
}

$startTime = Get-Date
for ($i = 1; $i -le $maxRetries; $i++) {
    $items = Get-ChildItem -Path $targetPath -Recurse -Force -ErrorAction SilentlyContinue

    if ($items.Count -eq 0) { break }

    $log += "Attempt #$i at $(Get-Date): Found $($items.Count) item(s)"

    foreach ($item in $items) {
        try {
            if ($item.PSIsContainer) {
                Remove-Item -Path $item.FullName -Recurse -Force -ErrorAction Stop
            } else {
                Remove-Item -Path $item.FullName -Force -ErrorAction Stop
            }
            $deletedItems += $item.FullName
        } catch {
            $skippedItems += "$($item.FullName) — $($_.Exception.Message)"
        }
    }

    Start-Sleep -Seconds $waitSeconds
}

# Final check
$remaining = Get-ChildItem -Path $targetPath -Recurse -Force -ErrorAction SilentlyContinue
$status = if ($remaining.Count -eq 0) { "✅ Cleanup Successful" } else { "⚠️ Some Items Could Not Be Deleted" }

$endTime = Get-Date

# Generate HTML
$htmlContent = @"
<!DOCTYPE html>
<html><head><meta charset='UTF-8'><title>Cleanup Report</title>
<style>
body { font-family: Segoe UI, sans-serif; background: #f9f9f9; color: #333; margin: 20px; }
h1 { color: #2E8B57; }
.status { font-size: 1.2em; font-weight: bold; }
.success { color: green; }
.warning { color: orange; }
.section { margin-top: 20px; }
ul { padding-left: 20px; }
.container { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px #ccc; }
.footer { font-size: 0.9em; color: #888; margin-top: 30px; }
</style>
</head><body><div class='container'>
<h1>Temp Folder Cleanup Report</h1>
<div class='status $(if ($status -like '*Successful*') {'success'} else {'warning'})'>$status</div>
<div><strong>Folder:</strong> $targetPath</div>
<div><strong>Start Time:</strong> $startTime</div>
<div><strong>End Time:</strong> $endTime</div>

<div class='section'><h2>𐇑️ Deleted Items ($($deletedItems.Count))</h2>
<ul>
$($deletedItems | ForEach-Object { "<li>$_</li>" } | Out-String)
</ul></div>

<div class='section'><h2>𐊫 Skipped Items ($($skippedItems.Count))</h2>
<ul>
$($skippedItems | ForEach-Object { "<li>$_</li>" } | Out-String)
</ul></div>

<div class='section'><h2>𐃋 Log</h2>
<ul>
$($log | ForEach-Object { "<li>$_</li>" } | Out-String)
</ul></div>

<div class='footer'>$copyright on $(Get-Date)</div></div></body></html>
"@

# Output HTML
$htmlContent | Set-Content -Path $htmlReport -Encoding UTF8
Write-Output "Report saved to: $htmlReport"